"""seo.py — Hybrid Batch SEO generation for Indian cricket live Shorts.

SEO Output Format:
You are an elite YouTube Shorts SEO and metadata generation engine for Indian cricket live-stream clips.

Your ONLY job is to generate:

* Titles
* Descriptions
* Search terms
* Hashtags

STRICTLY optimized for:

* YouTube Shorts discovery
* CTR
* Retention
* Search relevance
* Live-stream conversion

You MUST obey ALL metadata constraints EXACTLY.

━━━━━━━━━━━━━━━━━━
YOUTUBE API HARD LIMITS
━━━━━━━━━━━━━━━━━━

TITLE:

* MAXIMUM 100 characters
* IDEAL RANGE: 55–85 chars
* NEVER exceed 100
* Front-load the most important keywords

DESCRIPTION:

* MAXIMUM 5000 chars
* IDEAL RANGE: 400–1200 chars
* First 150 chars MUST contain:

  * main match keyword
  * player/moment keyword
  * “IPL 2026” or tournament keyword
* NEVER generate walls of text
* NEVER use markdown
* NEVER use AI-style wording

SEARCH TERMS:

* Total combined length MUST stay under 500 characters
* Each term:

  * lowercase
  * 2–5 words
  * highly searchable
* NO generic spam:

  * cricket
  * viral
  * shorts
  * trending
* NEVER duplicate hashtags inside search terms
* Target:

  * 18–30 search terms max

HASHTAGS:

* EXACTLY 3–5 hashtags
* NEVER exceed 15 hashtags
* Must be:

  * match-specific
  * tournament-specific
  * team-specific
* NO spam hashtags

━━━━━━━━━━━━━━━━━━
CONTENT RULES
━━━━━━━━━━━━━━━━━━

Your writing style:

* Natural Hinglish
* Emotional but believable
* Like a passionate cricket fan
* NOT like ChatGPT
* NOT corporate
* NOT clickbait garbage

DO:

* MENTION CORRECT PLAYER NAMES. The input transcript is auto-generated by Whisper and contains PHONETIC ERRORS (e.g., "Chakris Gale" -> "Chris Gayle", "David Ortona" -> "David Warner").
* YOU MUST intelligently infer and silently correct these transcription mistakes based on cricket context before writing the metadata.
* Mention:

  * teams
  * player names (FIXED and CORRECTED)
  * match situation
  * wickets/runs/pressure moments
* Include:

  * “live match”
  * “match review”
  * “Hindi analysis”
  * “reaction”
  * “powerplay”
  * “live score”
    naturally when relevant

DO NOT:

* Use incorrect or phonetically misspelled player names (e.g., NEVER use "Chakris Gale", use "Chris Gayle").
* Use fake hype
* Use repetitive phrases
* Use emojis excessively
* Use markdown
* Use bullet spam
* Use hashtags in title unless necessary

━━━━━━━━━━━━━━━━━━
TITLE GENERATION RULES
━━━━━━━━━━━━━━━━━━

GOOD TITLE FORMAT: <TEAM1> vs <TEAM2> Live Match Today | <Moment> | IPL 2026

Examples:
DC vs KKR Live Match Today | KKR Chase Drama | IPL 2026
RCB vs CSK Live Match Today | Kohli Pressure Knock | IPL 2026
MI vs GT Live Match Today | Bumrah Deadly Spell | IPL 2026

TITLE REQUIREMENTS:

* Include BOTH teams
* Include “Live Match Today”
* Include emotional/context phrase
* Include tournament/year
* Avoid excessive punctuation
* Max 1 emoji allowed
* NEVER exceed 100 chars

━━━━━━━━━━━━━━━━━━
DESCRIPTION FORMAT
━━━━━━━━━━━━━━━━━━

STRICT TEMPLATE:

Line 1:

<TITLE>

Paragraph 1:
<2–3 factual match lines>

Paragraph 2:
<Natural Hindi/Hinglish analysis paragraph>

Paragraph 3:
<Short CTA for live stream/channel>

Then:
3–5 hashtags

Then:
Search Terms: <one search term per line>

━━━━━━━━━━━━━━━━━━
SEARCH TERM STRATEGY
━━━━━━━━━━━━━━━━━━

Search terms MUST target:

1. Main match
2. Tournament
3. Player moments
4. Hindi viewers
5. Live viewers
6. Reaction audience

GOOD:
dc vs kkr live
ipl 2026 live match
kkr batting collapse
dc vs kkr hindi commentary

BAD:
cricket
viral shorts
awesome match
sports

━━━━━━━━━━━━━━━━━━
OUTPUT FORMAT
━━━━━━━━━━━━━━━━━━

Return ONLY valid JSON.

NO markdown.
NO explanation.
NO commentary.

Schema:

{
"clips_seo": [
{
"clip_id": "clip1",
"title": "...",
"description": "...",
"hashtags": [
"#DCvsKKR",
"#IPL2026"
],
"search_terms": [
"dc vs kkr live",
"ipl 2026 live match"
]
}
]
}

━━━━━━━━━━━━━━━━━━
VALIDATION RULES
━━━━━━━━━━━━━━━━━━

Before returning output:

* Verify title <= 100 chars
* Verify description <= 5000 chars
* Verify hashtags count <= 5
* Verify total search_terms character count <= 500
* Remove duplicates
* Remove generic spam
* Ensure JSON is valid
* Ensure no field is empty

If constraints fail:
REGENERATE internally before responding.

NEVER explain failures.
ONLY return final valid JSON.


Rules:
  - search_terms and hashtags are SEPARATE. Never reuse hashtags as search_terms.
  - search_terms drive discoverability (teams, players, moments, intent).
  - hashtags drive category/trending (match, tournament, Shorts).
  - Description: emotional hook, core moment early, natural CTA.
"""
import json
import re
from pathlib import Path
from typing import List, Dict, Tuple

from utils.config import load_config
from utils.logger import get_logger
from utils.ai_client import AIClient

cfg = load_config()
log = get_logger("seo", cfg["logging"]["log_file"], cfg["logging"]["level"])
ai = AIClient()

STOP_WORDS = {
    "i", "me", "my", "you", "your", "we", "our", "they", "their", "this", "that", "these", "those",
    "am", "is", "are", "was", "were", "be", "been", "have", "has", "had", "do", "does", "did",
    "a", "an", "the", "and", "or", "but", "if", "as", "of", "to", "in", "on", "at", "for", "from",
    "with", "by", "about", "into", "over", "under", "again", "then", "here", "there", "when", "where",
    "why", "how", "all", "any", "more", "most", "some", "such", "no", "nor", "not", "only", "very",
}

GENERIC_TAGS = {
    "cricket", "shorts", "viral", "trending", "youtube", "video", "sports",
    "highlight", "highlights", "amazing", "awesome", "incredible", "wow"
}

# ── Proven high-CTR title formulas for cricket Shorts ──────────────────────────
# %PLAYER% = player name, %MOMENT% = what happened, %CONTEXT% = match context
# %TREND% = trending topic, %STAT% = a number/stat
TITLE_FORMULAS = [
    # Formula A: Curiosity-gap + drama
    "Nobody Expected %PLAYER% To Do THIS 😱 | %CONTEXT%",
    "%PLAYER% ne kya kar diya yaar 😤 | %MOMENT%",
    "Wait For It… %PLAYER%'s %MOMENT% Changed Everything 🔥",
    "This %MOMENT% by %PLAYER% broke the internet 💥 | %CONTEXT%",
    # Formula B: Stat-shock
    "%STAT% in %CONTEXT% — %PLAYER% is Built Different 🏏",
    "Only %PLAYER% Can Do This In %CONTEXT% 👀",
    # Formula C: Live stream hook
    "🔴 LIVE NOW: %TREND% | %PLAYER%'s Best Shots REACTION",
    "Watch Full Match LIVE 🔴 | %PLAYER% %MOMENT% Highlights",
]


def inject_trend_topics_into_tags(
    base_tags: List[str],
    trend_topics: List[str],
    player_name: str = ""
) -> List[str]:
    if not trend_topics:
        return base_tags
    result = base_tags.copy()
    seen_lower = {tag.lower() for tag in result}
    for topic in trend_topics[:3]:
        topic_lower = topic.lower()
        if topic_lower in seen_lower:
            continue
        if player_name:
            combo = f"{player_name} {topic_lower}"
            if combo not in seen_lower:
                result.append(combo)
                seen_lower.add(combo)
        if topic_lower not in seen_lower:
            result.append(topic_lower)
            seen_lower.add(topic_lower)
    return result


def ensure_trend_in_title(title: str, trend_topics: List[str]) -> str:
    """
    Inject trend into title ONLY if it fits naturally — never prepend blindly.
    Preserves curiosity gap structure.
    """
    if not trend_topics:
        return title[:100]
    title_lower = title.lower()
    for trend in trend_topics:
        trend_words = trend.lower().split()
        if len(trend_words) >= 2 and " ".join(trend_words[:2]) in title_lower:
            return title[:100]
        if trend.lower() in title_lower:
            return title[:100]
    # Append as context tag rather than prepend — keeps hook intact
    top = trend_topics[0]
    candidate = f"{title} | {top}"
    return candidate[:100] if len(candidate) <= 100 else title[:100]


def validate_hinglish_content(text: str) -> Tuple[bool, str]:
    hindi_words = {
        'ka', 'ki', 'ke', 'ko', 'mein', 'se', 'par', 'aur', 'hai', 'tha', 'thi',
        'dhamaakedaar', 'jabardast', 'shandaar', 'kya', 'yeh', 'toh', 'bhi',
        'maara', 'khela', 'dekho', 'bolo', 'arey', 'yaar', 'bhai', 'log', 'ne',
    }
    words = text.lower().split()
    count = sum(1 for w in words if w in hindi_words)
    if count >= 2:
        return True, "hinglish"
    elif count == 1:
        return True, "light_hinglish"
    return True, "english"


def validate_emoji_usage(text: str) -> bool:
    emoji_pattern = re.compile(
        r"[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF"
        r"\U0001F680-\U0001F6FF\U0001F1E0-\U0001F1FF"
        r"\U00002700-\U000027BF\U00002600-\U000026FF]"
    )
    return len(emoji_pattern.findall(text)) <= 5


def _validate_search_terms(terms: List[str], min_words: int = 2) -> List[str]:
    """Validate search terms: must be 2+ words, not generic spam."""
    if not terms:
        return []
    valid = []
    for term in terms:
        tl = term.lower().strip()
        if not tl:
            continue
        if len(tl.split()) < min_words:
            continue
        if tl in GENERIC_TAGS:
            continue
        if set(tl.split()).issubset(GENERIC_TAGS):
            continue
        valid.append(term)
    return valid


def _extract_keywords(text: str, limit: int = 14) -> List[str]:
    words = re.findall(r"[A-Za-z0-9']+", (text or "").lower())
    keywords = [w for w in words if w not in STOP_WORDS and len(w) > 2]
    freq: Dict[str, int] = {}
    for w in keywords:
        freq[w] = freq.get(w, 0) + 1
    return [k for k, _ in sorted(freq.items(), key=lambda x: x[1], reverse=True)[:limit]]


def _enforce_limits(item: Dict) -> Dict:
    title = (item.get("title", "") or "")[:100]
    description = (item.get("description", "") or "")[:5000]

    hashtags = item.get("hashtags", []) or []
    hashtags = [h if h.startswith("#") else f"#{h}" for h in hashtags]
    hashtags = list(dict.fromkeys(hashtags))[:5]

    search_terms = item.get("search_terms", []) or []
    cleaned_terms = []
    total_chars = 0
    for term in search_terms:
        t = str(term).strip().lower()
        if not t or len(t.split()) < 2:
            continue
        if t in GENERIC_TAGS:
            continue
        if t in {x.lower() for x in hashtags}:
            continue
        extra = len(t) + (2 if cleaned_terms else 0)
        if total_chars + extra > 500:
            break
        cleaned_terms.append(t)
        total_chars += extra

    return {
        **item,
        "title": title,
        "description": description,
        "hashtags": hashtags,
        "search_terms": cleaned_terms,
    }


def batch_generate_seo(clips: List[Dict], domain: str = "cricket", region: str = "IN") -> List[Dict]:
    from trends import get_trending_context
    import time

    video_title = ""
    live_stream_url = ""
    meta_file = Path(cfg["paths"]["input"]) / "video_metadata.json"
    if meta_file.exists():
        try:
            with open(meta_file, "r", encoding="utf-8") as f:
                meta = json.load(f)
                video_title = meta.get("title", "")
                live_stream_url = meta.get("live_stream_url", "")
        except Exception:
            pass

    trend = get_trending_context(domain=domain, region=region, video_title=video_title)
    live_stream_url = live_stream_url or trend.get("live_stream_url", "")

    clips_context = []
    for c in clips:
        clips_context.append({
            "clip_id": c["clip_id"],
            "transcript": c["text"],
            "local_keywords": _extract_keywords(c["text"]),
        })

    trend_topics_str = ", ".join(trend.get("topics", [])) or "IPL 2026, cricket live"
    scorecard = trend.get("scorecard", "")

    system_instr = (
        "You are a strict YouTube Shorts SEO engine for Indian cricket live-stream clips. "
        "Generate valid JSON only. Obey all metadata limits exactly. "
        "No markdown, no explanation, no extra text."
    )

    live_cta = (
        f"🔴 Watch LIVE: {live_stream_url}" if live_stream_url
        else "🔴 Match chal raha hai LIVE — channel pe aao."
    )

    prompt = f"""
Match: {video_title}
Scorecard: {scorecard}
Trending Topics: {trend_topics_str}
Live Stream CTA: {live_cta}

For each clip, generate:
- title (<=100 chars)
- description (<=5000 chars)
- hashtags (exactly 3-5)
- search_terms (18-30 terms, lowercase, 2+ words, total <=500 chars)

Use this clip data:
{json.dumps(clips_context, ensure_ascii=False, indent=2)}

Hard rules:
- Title: must include teams + live match context + moment + IPL/year when relevant
- Description: factual, natural Hinglish, first 150 chars must be strong and searchable
- Hashtags: specific only
- Search terms: no generic spam, no hashtag duplicates

Return JSON exactly like:
{{
  "clips_seo": [
    {{
      "clip_id": "clip1",
      "title": "...",
      "description": "...",
      "hashtags": ["#A", "#B", "#C"],
      "search_terms": ["term one", "term two"]
    }}
  ]
}}
"""

    delay = 0
    last_error = None

    for attempt in range(3):
        try:
            if delay:
                time.sleep(delay)

            response_text = ai.generate_text(prompt, system_instruction=system_instr)
            json_match = re.search(r"\{.*\}", response_text, re.DOTALL)
            if not json_match:
                raise ValueError("No JSON returned by AI.")

            data = json.loads(json_match.group(0))
            results = data.get("clips_seo", [])
            if not results:
                raise ValueError("Empty clips_seo.")

            final_results = []
            trend_topics_list = trend.get("topics", [])
            hashtags_from_trend = trend.get("tags", ["#Shorts", "#Cricket"])

            for c in clips:
                seo = next((item for item in results if item.get("clip_id") == c["clip_id"]), {})

                primary_title = seo.get("title", f"Cricket Highlights | {c['clip_id']}")
                title = ensure_trend_in_title(primary_title, trend_topics_list)

                final_results.append(_enforce_limits({
                    "clip_id": c["clip_id"],
                    "title": title,
                    "description": seo.get("description", ""),
                    "hashtags": seo.get("hashtags", hashtags_from_trend[:5]),
                    "search_terms": seo.get("search_terms", []),
                    "trend_topics": trend_topics_list,
                    "live_stream_url": live_stream_url,
                }))

            return final_results

        except Exception as e:
            last_error = e
            msg = str(e)
            if "429" in msg or "593" in msg:
                delay = 8 if attempt == 0 else 20 if attempt == 1 else 45
                continue
            delay = 5

    raise ValueError(f"SEO generation failed after retries: {last_error}")


def generate_seo(clip_text: str, clip_id: str) -> Dict:
    results = batch_generate_seo([{"clip_id": clip_id, "text": clip_text}])
    return results[0] if results else {}


def process_all_seo(highlights_path: str, output_dir: str):
    h_path = Path(highlights_path)
    if not h_path.exists():
        log.error("Highlights not found: %s", h_path)
        return

    with open(h_path, "r", encoding="utf-8") as f:
        import yaml
        highlights = yaml.safe_load(f) or {}

    Path(output_dir).mkdir(parents=True, exist_ok=True)

    clips_to_process = [
        {"clip_id": clip_id, "text": info.get("text", "Cricket Live")}
        for clip_id, info in highlights.items()
    ]

    batch_size = 3
    all_results = []

    import time
    for i in range(0, len(clips_to_process), batch_size):
        batch = clips_to_process[i:i + batch_size]
        results = batch_generate_seo(batch)
        all_results.extend(results)

        # small pause to reduce 429 / 593 pressure
        if i + batch_size < len(clips_to_process):
            time.sleep(8)

    out_path = Path(output_dir) / "seo_results.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)

    return str(out_path)


if __name__ == "__main__":
    process_all_seo("highlights/video.yaml", "shorts/test")