#!/usr/bin/env python3
"""
analytics_report.py — Generate a comprehensive HTML analytics report
from collected SEO performance data + YouTube analytics logs.

Usage:
  python -m automation.seo.analytics_report                          # latest only
  python -m automation.seo.analytics_report --output report.html     # custom path
  python -m automation.seo.analytics_report --open                   # open in browser
"""

import json
import sys
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional
import base64
from io import BytesIO

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(ROOT))

HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>yt-clips Analytics Report</title>
<style>
  :root {{ --bg: #0d1117; --card: #161b22; --border: #30363d; --text: #c9d1d9; --muted: #8b949e; --accent: #58a6ff; --green: #3fb950; --red: #f85149; --yellow: #d29922; }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:-apple-system,'Segoe UI',Helvetica,Arial,sans-serif; background:var(--bg); color:var(--text); padding:20px; }}
  .container {{ max-width:1200px; margin:0 auto; }}
  h1 {{ font-size:28px; margin-bottom:4px; }}
  h2 {{ font-size:20px; margin:28px 0 12px; color:var(--accent); border-bottom:1px solid var(--border); padding-bottom:8px; }}
  .subtitle {{ color:var(--muted); font-size:14px; margin-bottom:24px; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:12px; margin-bottom:24px; }}
  .card {{ background:var(--card); border:1px solid var(--border); border-radius:8px; padding:16px; }}
  .card .label {{ font-size:12px; text-transform:uppercase; color:var(--muted); letter-spacing:0.5px; }}
  .card .value {{ font-size:28px; font-weight:600; margin-top:4px; }}
  .card .delta {{ font-size:13px; margin-top:2px; }}
  .up {{ color:var(--green); }} .down {{ color:var(--red); }} .flat {{ color:var(--yellow); }}
  .bar {{ height:6px; border-radius:3px; background:var(--border); margin-top:8px; overflow:hidden; }}
  .bar-fill {{ height:100%; border-radius:3px; transition:width .5s; }}
  table {{ width:100%; border-collapse:collapse; margin:12px 0; font-size:14px; }}
  th {{ text-align:left; padding:8px 10px; border-bottom:2px solid var(--border); color:var(--muted); font-weight:600; font-size:12px; text-transform:uppercase; }}
  td {{ padding:8px 10px; border-bottom:1px solid var(--border); }}
  tr:hover td {{ background:rgba(88,166,255,0.05); }}
  .tag {{ display:inline-block; padding:2px 8px; border-radius:4px; font-size:11px; font-weight:600; background:rgba(56,139,253,0.15); color:var(--accent); margin:1px; }}
  .chart-bar {{ display:inline-block; height:14px; border-radius:2px; margin-right:4px; vertical-align:middle; min-width:2px; }}
  .section {{ background:var(--card); border:1px solid var(--border); border-radius:8px; padding:20px; margin-bottom:16px; }}
  .flex {{ display:flex; gap:16px; flex-wrap:wrap; }}
  .stat-row {{ display:flex; justify-content:space-between; padding:4px 0; font-size:13px; }}
  .stat-row .lbl {{ color:var(--muted); }} .stat-row .val {{ font-weight:500; }}
  .mini-chart {{ display:flex; align-items:flex-end; gap:2px; height:40px; margin:12px 0; }}
  .mini-bar {{ width:8px; border-radius:2px 2px 0 0; min-height:2px; }}
  .no-data {{ color:var(--muted); font-style:italic; padding:20px; text-align:center; }}
  .badge {{ display:inline-block; padding:2px 8px; border-radius:10px; font-size:11px; font-weight:600; }}
  .badge-green {{ background:rgba(63,185,80,0.15); color:var(--green); }}
  .badge-red {{ background:rgba(248,81,73,0.15); color:var(--red); }}
  .badge-yellow {{ background:rgba(210,153,34,0.15); color:var(--yellow); }}
  .footer {{ text-align:center; color:var(--muted); font-size:12px; margin-top:40px; padding:20px; }}
</style>
</head>
<body>
<div class="container">
{content}
<div class="footer">Generated by yt-clips analytics_report.py · {generated_at}</div>
</div>
</body>
</html>"""


def fmt(n, suffix=""):
    if n is None:
        return "—"
    if isinstance(n, float):
        return f"{n:.1f}{suffix}"
    return f"{n:,}{suffix}"


def mini_sparkline(vals, color="#58a6ff", height=40, bar_width=8):
    if not vals:
        return ""
    mx = max(vals) or 1
    bars = "".join(
        f'<div class="mini-bar" style="height:{max(2, v/mx*height):.0f}px;background:{color}"></div>'
        for v in vals[-24:]
    )
    return f'<div class="mini-chart">{bars}</div>'


def sparkbar(val, max_val, color="#58a6ff"):
    pct = (val / max_val * 100) if max_val > 0 else 0
    return f'<div class="bar"><div class="bar-fill" style="width:{pct:.0f}%;background:{color}"></div></div>'


def load_performance_data() -> Dict:
    path = ROOT / "data/seo_performance.json"
    if not path.exists():
        return {"clips": [], "title_patterns": {}, "hashtag_performance": {},
                "hooks_performance": {}, "ctas_performance": {},
                "model_performance": {}, "benchmark_history": []}
    with open(path) as f:
        return json.load(f)


def load_latest_analytics() -> Optional[Dict]:
    log_dir = ROOT / "logs"
    files = sorted(log_dir.glob("analytics_*.json"), reverse=True)
    if not files:
        return None
    with open(files[0]) as f:
        return json.load(f)


def load_all_analytics() -> List[Dict]:
    log_dir = ROOT / "logs"
    files = sorted(log_dir.glob("analytics_*.json"))
    results = []
    for p in files:
        with open(p) as f:
            data = json.load(f)
            ts = p.stem.replace("analytics_", "").replace("_", "T")
            results.append({"timestamp": ts, "data": data})
    return results


def build_overview_section(pd: Dict, ad: Optional[Dict], history: List[Dict]) -> str:
    clips = pd.get("clips", [])
    total_clips = len(clips)
    unique_ids = len(set(c["clip_id"] for c in clips))
    scores = [c["performance_score"] for c in clips]
    avg_score = sum(scores) / len(scores) if scores else 0
    max_score = max(scores) if scores else 0
    min_score = min(scores) if scores else 0

    total_shorts_views = 0
    total_shorts_likes = 0
    total_shorts_comments = 0
    total_live_views = 0
    shorts_count = 0
    live_count = 0
    if ad:
        for s in ad.get("shorts", []):
            total_shorts_views += s.get("views", 0)
            total_shorts_likes += s.get("likes", 0)
            total_shorts_comments += s.get("comments", 0)
            shorts_count += 1
        for lv in ad.get("lives", []):
            total_live_views += lv.get("views", 0)
            live_count += 1

    # Trend: views per day over the analytics history
    daily_views = []
    daily_labels = []
    for h in history:
        d = h["data"]
        v = sum(s.get("views", 0) for s in d.get("shorts", []))
        daily_views.append(v)
        ts = h["timestamp"][:10]
        daily_labels.append(ts)

    view_trend = ""
    if len(daily_views) >= 2:
        trend = daily_views[-1] - daily_views[-2]
        trend_class = "up" if trend > 0 else ("down" if trend < 0 else "flat")
        trend_str = f"+{trend}" if trend > 0 else str(trend)
        view_trend = f'<span class="{trend_class}">{trend_str}</span> views vs yesterday'

    return f"""
    <h1>📊 yt-clips Analytics Dashboard</h1>
    <p class="subtitle">
      {total_clips} clips tracked · {unique_ids} unique videos · {shorts_count} shorts in latest fetch · {view_trend}
    </p>
    <div class="grid">
      <div class="card">
        <div class="label">Avg Performance Score</div>
        <div class="value">{avg_score:.3f}</div>
        <div class="delta">range: {min_score:.2f} – {max_score:.2f}</div>
        {sparkbar(avg_score, 1.0, '#58a6ff')}
      </div>
      <div class="card">
        <div class="label">Total Shorts Views</div>
        <div class="value">{fmt(total_shorts_views)}</div>
        <div class="delta">{shorts_count} shorts · avg {fmt(total_shorts_views / max(1, shorts_count))}/short</div>
        {sparkbar(total_shorts_views / max(1, shorts_count), 500, '#3fb950')}
      </div>
      <div class="card">
        <div class="label">Total Engagement</div>
        <div class="value">{fmt(total_shorts_likes + total_shorts_comments)}</div>
        <div class="delta">👍 {fmt(total_shorts_likes)} likes · 💬 {fmt(total_shorts_comments)} comments</div>
      </div>
      <div class="card">
        <div class="label">Live Stream Views</div>
        <div class="value">{fmt(total_live_views)}</div>
        <div class="delta">{live_count} streams</div>
      </div>
    </div>
    <div class="section">
      <h2>📈 Daily Shorts Views</h2>
      {mini_sparkline(daily_views, '#3fb950') if daily_views else '<div class="no-data">No historical data</div>'}
      <div style="display:flex;gap:12px;flex-wrap:wrap;font-size:12px;color:var(--muted);margin-top:4px;">
        {"".join(f'<span>{l}</span>' for l in daily_labels[-7:])}
      </div>
    </div>
    """


def build_performance_scores_section(pd: Dict) -> str:
    clips = pd.get("clips", [])
    if not clips:
        return '<div class="section"><h2>📊 Performance Scores</h2><div class="no-data">No data yet</div></div>'

    scores = [(c["performance_score"], c.get("clip_id", "?"), c.get("timestamp", "")[:10]) for c in clips]
    scores.sort(key=lambda x: -x[0])

    rows = ""
    for i, (score, cid, ts) in enumerate(scores[:20]):
        color = "#3fb950" if score >= 0.5 else ("#d29922" if score >= 0.35 else "#f85149")
        pct = score / max(s[0] for s in scores) * 100
        badge = "badge-green" if score >= 0.5 else ("badge-yellow" if score >= 0.35 else "badge-red")
        rank = f'<span class="badge {badge}">#{i+1}</span>'
        rows += f"<tr><td>{rank}</td><td style='font-family:monospace;font-size:12px'>{cid[:12]}</td><td>{ts}</td><td>{score:.4f}</td><td><div class='bar'><div class='bar-fill' style='width:{pct:.0f}%;background:{color}'></div></div></td></tr>"

    return f"""
    <div class="section">
      <h2>📊 Performance Scores</h2>
      <table>
        <tr><th>Rank</th><th>Video ID</th><th>Date</th><th>Score</th><th></th></tr>
        {rows}
      </table>
      {f'<div style="color:var(--muted);font-size:13px">… and {len(scores) - 20} more</div>' if len(scores) > 20 else ''}
    </div>
    """


def build_title_patterns_section(pd: Dict) -> str:
    tp = pd.get("title_patterns", {})
    if not tp:
        return '<div class="section"><h2>🎯 Title Patterns</h2><div class="no-data">No patterns learned yet</div></div>'

    patterns = [(k, v["avg_score"], v["count"], v["total_score"]) for k, v in tp.items()]
    patterns.sort(key=lambda x: -x[1])

    rows = ""
    for pattern, avg, count, total in patterns:
        readable = pattern.replace("_", " · ").replace(":", ": ")
        color = "#3fb950" if avg >= 0.5 else ("#d29922" if avg >= 0.35 else "#f85149")
        badge = "badge-green" if avg >= 0.5 else ("badge-yellow" if avg >= 0.35 else "badge-red")
        rows += f"""
        <tr>
          <td style="font-family:monospace;font-size:12px">{pattern[:60]}</td>
          <td><span class="badge {badge}">{avg:.3f}</span></td>
          <td>{count}x</td>
          <td><div class="bar"><div class="bar-fill" style="width:{avg*100:.0f}%;background:{color}"></div></div></td>
        </tr>"""

    best = patterns[0] if patterns else None
    worst = patterns[-1] if len(patterns) > 1 else None
    insights = ""
    if best:
        insights += f'<div style="margin-bottom:8px">✅ <strong>Best pattern:</strong> avg {best[1]:.3f} across {best[2]} clips — <code style="font-size:12px">{best[0][:60]}</code></div>'
    if worst and worst[1] < 0.4:
        insights += f'<div>❌ <strong>Worst pattern:</strong> avg {worst[1]:.3f} across {worst[2]} clips — <code style="font-size:12px">{worst[0][:60]}</code></div>'

    return f"""
    <div class="section">
      <h2>🎯 Title Patterns</h2>
      {insights}
      <table>
        <tr><th>Pattern</th><th>Avg Score</th><th>Count</th><th></th></tr>
        {rows}
      </table>
    </div>
    """


def build_hashtag_section(pd: Dict) -> str:
    hp = pd.get("hashtag_performance", {})
    if not hp:
        return '<div class="section"><h2>#️⃣ Hashtag Performance</h2><div class="no-data">No hashtag data collected yet</div></div>'

    entries = [(k, sum(v) / len(v) if v else 0, len(v)) for k, v in hp.items()]
    entries.sort(key=lambda x: -x[1])

    rows = ""
    for tag, avg, count in entries:
        color = "#3fb950" if avg >= 0.5 else ("#d29922" if avg >= 0.35 else "#f85149")
        rows += f"<tr><td style='font-family:monospace'>{tag}</td><td>{avg:.3f}</td><td>{count}x</td><td><div class='bar'><div class='bar-fill' style='width:{avg*100:.0f}%;background:{color}'></div></div></td></tr>"

    return f"""
    <div class="section">
      <h2>#️⃣ Hashtag Performance</h2>
      <table>
        <tr><th>Hashtag Feature</th><th>Avg Score</th><th>Count</th><th></th></tr>
        {rows}
      </table>
    </div>
    """


def build_model_performance_section(pd: Dict) -> str:
    mp = pd.get("model_performance", {})
    if not mp:
        return f"""
        <div class="section">
          <h2>🤖 Model Performance</h2>
          <div class="no-data">
            No model/provider data yet — enable <code>auto_benchmark</code> in config.yaml<br>
            or set <code>_generated_by_provider</code> / <code>_generated_by_model</code> in SEO metadata.
          </div>
        </div>
        """

    entries = [(k, v["avg_score"], v["count"]) for k, v in mp.items()]
    entries.sort(key=lambda x: -x[1])

    rows = ""
    for key, avg, count in entries:
        color = "#3fb950" if avg >= 0.5 else "#d29922"
        rows += f"<tr><td>{key}</td><td>{avg:.3f}</td><td>{count}x</td><td><div class='bar'><div class='bar-fill' style='width:{avg*100:.0f}%;background:{color}'></div></div></td></tr>"

    best = pd.get("current_best_provider"), pd.get("current_best_model")
    best_str = f"{best[0]}/{best[1]}" if best[0] else "Not selected"

    return f"""
    <div class="section">
      <h2>🤖 Model Performance</h2>
      <div style="margin-bottom:12px;font-size:14px">🏆 <strong>Current best:</strong> {best_str}</div>
      <table>
        <tr><th>Provider/Model</th><th>Avg Score</th><th>Count</th><th></th></tr>
        {rows}
      </table>
    </div>
    """


def build_latest_shorts_section(ad: Optional[Dict]) -> str:
    if not ad:
        return '<div class="section"><h2>🎬 Latest Shorts</h2><div class="no-data">No analytics data</div></div>'

    shorts = ad.get("shorts", [])
    if not shorts:
        return f'<div class="section"><h2>🎬 Latest Shorts</h2><div class="no-data">No shorts found in latest fetch</div></div>'

    shorts_sorted = sorted(shorts, key=lambda x: -x.get("views", 0))
    rows = ""
    for s in shorts_sorted[:15]:
        title = s.get("title", "?")[:50]
        views = s.get("views", 0)
        likes = s.get("likes", 0)
        comments = s.get("comments", 0)
        eng = ((likes + comments) / max(1, views)) * 100
        cid = s.get("id", "")[:10]
        color = "#3fb950" if views >= 200 else ("#d29922" if views >= 100 else "#f85149")
        rows += f"<tr><td style='font-family:monospace;font-size:12px'>{cid}</td><td>{title}</td><td>{fmt(views)}</td><td>{fmt(likes)}</td><td>{fmt(comments)}</td><td>{eng:.1f}%</td><td><div class='bar'><div class='bar-fill' style='width:{min(100, views/20):.0f}%;background:{color}'></div></div></td></tr>"

    return f"""
    <div class="section">
      <h2>🎬 Latest Shorts (n={len(shorts)})</h2>
      <table>
        <tr><th>ID</th><th>Title</th><th>Views</th><th>Likes</th><th>Comments</th><th>Eng Rate</th><th></th></tr>
        {rows}
      </table>
    </div>
    """


def build_top_performers_section(ad: Optional[Dict], pd: Dict) -> str:
    if not ad:
        return ""
    all_content = ad.get("shorts", []) + ad.get("videos", []) + ad.get("lives", [])
    if not all_content:
        return ""

    top = sorted(all_content, key=lambda x: -x.get("views", 0))[:5]
    rows = ""
    for i, item in enumerate(top):
        title = item.get("title", "?")[:60]
        views = item.get("views", 0)
        likes = item.get("likes", 0)
        badge = "badge-green" if i < 3 else "badge-yellow"
        rows += f"<tr><td><span class='badge {badge}'>#{i+1}</span></td><td>{title}</td><td>{fmt(views)}</td><td>{fmt(likes)}</td></tr>"

    return f"""
    <div class="section">
      <h2>🏆 Top Performers (All Content)</h2>
      <table>
        <tr><th>Rank</th><th>Title</th><th>Views</th><th>Likes</th></tr>
        {rows}
      </table>
    </div>
    """


def build_feature_importance_section(pd: Dict) -> str:
    fi = pd.get("feature_importance", {})
    if not fi:
        return ""
    rows = ""
    for feat, data in sorted(fi.items(), key=lambda x: -abs(x[1]["delta"])):
        delta = data["delta"]
        color = "#3fb950" if delta > 0 else "#f85149"
        arrow = "▲" if delta > 0 else "▼"
        label = feat.replace("has_", "").replace("_", " ").title()
        rows += f"<tr><td>{arrow} {label}</td><td style='color:{color}'>{delta:+.3f}</td><td>{data['count_with']} / {data['count_without']}</td><td style='color:{color}'>{'Positive' if delta > 0 else 'Negative'}</td></tr>"
    if not rows:
        return ""
    return f"""
    <div class="section">
      <h2>📊 Feature Importance</h2>
      <p style="color:var(--muted);font-size:13px;margin-bottom:8px">
        Score delta when feature is present vs absent (time-decayed)
      </p>
      <table>
        <tr><th>Feature</th><th>Delta</th><th>Samples (yes/no)</th><th>Impact</th></tr>
        {rows}
      </table>
    </div>
    """


def build_llm_insights_section(pd: Dict) -> str:
    llm = pd.get("llm_insights", [])
    if not llm:
        return ""
    latest = llm[-1].get("insights", "")
    ts = llm[-1].get("timestamp", "")[:10]
    return f"""
    <div class="section">
      <h2>🧠 AI-Powered Insights</h2>
      <p style="color:var(--muted);font-size:13px">Generated from performance data · {ts}</p>
      <div style="background:rgba(88,166,255,0.08);border-left:3px solid var(--accent);padding:12px 16px;margin-top:8px;line-height:1.6;white-space:pre-wrap;font-size:14px">
        {latest}
      </div>
    </div>
    """


def build_recommendations_section(pd: Dict) -> str:
    clips = pd.get("clips", [])
    tp = pd.get("title_patterns", {})
    hp = pd.get("hashtag_performance", {})

    recs = []

    if tp:
        patterns = [(k, v["avg_score"]) for k, v in tp.items() if v["count"] >= 2]
        patterns.sort(key=lambda x: -x[1])
        if patterns:
            best = patterns[0]
            recs.append(f"Title pattern <code>{best[0][:50]}</code> scores {best[1]:.3f} — use similar structure")
        if len(patterns) > 1:
            worst = patterns[-1]
            if worst[1] < 0.35:
                recs.append(f"Avoid title pattern <code>{worst[0][:50]}</code> (avg {worst[1]:.3f})")

    if clips:
        with_pipe = [c for c in clips if c["features"].get("has_pipe_format")]
        without_pipe = [c for c in clips if not c["features"].get("has_pipe_format")]
        if with_pipe and without_pipe:
            avg_pipe = sum(c["performance_score"] for c in with_pipe) / len(with_pipe)
            avg_no = sum(c["performance_score"] for c in without_pipe) / len(without_pipe)
            if avg_pipe > avg_no * 1.1:
                recs.append(f"Pipe format (Team vs Team | Tournament) outperforms by {((avg_pipe/avg_no)-1)*100:.0f}%")
    if hp:
        entries = [(k, sum(v)/len(v) if v else 0) for k, v in hp.items()]
        entries.sort(key=lambda x: -x[1])
        if entries:
            best_h = entries[0]
            recs.append(f"Hashtag pattern <code>{best_h[0]}</code> most effective (avg {best_h[1]:.3f})")

    if not recs:
        recs.append("More data needed for recommendations — keep publishing!")

    items = "".join(f"<li style='margin-bottom:6px'>✅ {r}</li>" for r in recs)
    return f"""
    <div class="section">
      <h2>💡 Recommendations</h2>
      <ul style="padding-left:20px;line-height:1.6">{items}</ul>
    </div>
    """


def generate_html():
    pd = load_performance_data()
    ad = load_latest_analytics()
    history = load_all_analytics()

    sections = [
        build_overview_section(pd, ad, history),
        build_top_performers_section(ad, pd),
        build_latest_shorts_section(ad),
        build_performance_scores_section(pd),
        build_feature_importance_section(pd),
        build_title_patterns_section(pd),
        build_hashtag_section(pd),
        build_model_performance_section(pd),
        build_llm_insights_section(pd),
        build_recommendations_section(pd),
    ]

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    content = "\n".join(sections)
    return HTML.format(content=content, generated_at=now)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate analytics HTML report")
    parser.add_argument("-o", "--output", default="reports/analytics/analytics_report.html",
                        help="Output HTML path (default: reports/analytics/analytics_report.html)")
    parser.add_argument("--open", action="store_true", help="Open in browser")
    args = parser.parse_args()

    html = generate_html()
    out_path = Path(args.output)
    out_path.parent.mkdir(exist_ok=True)
    out_path.write_text(html)
    size_kb = len(html) / 1024
    print(f"Report saved: {out_path} ({size_kb:.0f} KB)")

    if args.open:
        import subprocess, sys
        if sys.platform == "darwin":
            subprocess.run(["open", str(out_path)], check=True)
        print("Opened in browser")


if __name__ == "__main__":
    main()
